language: node_js
node_js:
  - "7"

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/docker-cache/

env:
  global:
    - COMPONENT=${cut -d "/" -f 2 <<< "$TRAVIS_REPO_SLUG"}
    - DOCKER_CACHE_FILE=/home/travis/docker-cache/cache.tar.gz
  matrix:
    - DOCKER_IMAGE=craycraig/$COMPONENT-armv7l
      CI_MASTER=true
    - DOCKER_IMAGE=craycraig/$COMPONENT-x86_64
      BASEIMAGE=resin\\/nuc-node:7.2.1
      CI_MASTER=false

before_install:
  - if [ -f $DOCKER_CACHE_FILE ]; then
      gunzip -c $DOCKER_CACHE_FILE | docker load || true;
    fi
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - if [ "$BASEIMAGE" ] ; then sed -i "s/^FROM .*/FROM $BASEIMAGE/" Dockerfile ; fi
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - git remote set-url origin "https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git"

script:
  - if [[ ${TRAVIS_PULL_REQUEST} != "false" ]]; then
      docker build -t $DOCKER_IMAGE:$TRAVIS_PULL_REQUEST_BRANCH .;
      echo $TRAVIS_PULL_REQUEST_BRANCH;
      versionist -d;
    fi
  - if [[ ${TRAVIS_PULL_REQUEST} == "false" && -z ${TRAVIS_TAG} && ${TRAVIS_BRANCH} == "master" && ${CI_MASTER} == "true" ]]; then
      versionist;
    fi
  - if [[ ${TRAVIS_PULL_REQUEST} == "false" && -n ${TRAVIS_TAG} ]]; then
      docker build -t $DOCKER_IMAGE:$TRAVIS_TAG .;
    fi

after_success:
  - if [[ ${TRAVIS_PULL_REQUEST} != "false" ]]; then
      docker push $DOCKER_IMAGE:$TRAVIS_PULL_REQUEST_BRANCH;
    fi
  - if [[ ${TRAVIS_PULL_REQUEST} == "false" && -n ${TRAVIS_TAG} ]]; then
      docker push $DOCKER_IMAGE:$TRAVIS_TAG;
    fi
