language: node_js
node_js:
  - "7"

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/docker-cache/

env:
  global:
    - COMPONENT=versionist-example
    - DOCKER_CACHE_FILE=/home/travis/docker-cache/cache.tar.gz
    - DOCKER_IMAGE=craycraig/$COMPONENT-armv7l
  matrix:
    - DOCKER_IMAGE=craycraig/$COMPONENT-armv7l

before_install:
  - if [ -f $DOCKER_CACHE_FILE ]; then
      gunzip -c $DOCKER_CACHE_FILE | docker load || true;
    fi
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - if [ "$BASEIMAGE" ] ; then sed -i "s/^FROM .*/FROM $BASEIMAGE/" Dockerfile ; fi
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - git remote set-url origin https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git

script:
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - if [[ ${TRAVIS_PULL_REQUEST} != "false" ]]; then
      docker build -t $DOCKER_IMAGE:$TRAVIS_PULL_REQUEST_BRANCH .;
      echo $TRAVIS_PULL_REQUEST_BRANCH;
      versionist -d;
    fi
  - if [[ ${TRAVIS_PULL_REQUEST} == "false" && -z ${TRAVIS_TAG} && ${TRAVIS_BRANCH} == "master" ]]; then
      versionist;
    fi
  - if [[ ${TRAVIS_PULL_REQUEST} == "false" && -n ${TRAVIS_TAG} ]]; then
      docker build -t $DOCKER_IMAGE:$TRAVIS_TAG .;
    fi

after_success:
  - if [[ ${TRAVIS_PULL_REQUEST} != "false" ]]; then
      docker push $DOCKER_IMAGE:$TRAVIS_PULL_REQUEST_BRANCH;
    fi
  - if [[ ${TRAVIS_PULL_REQUEST} == "false" && -z ${TRAVIS_TAG} && ${TRAVIS_BRANCH} == "master" ]]; then
      echo "noop";
    fi
  - if [[ ${TRAVIS_PULL_REQUEST} == "false" && -n ${TRAVIS_TAG} ]]; then
      docker push $DOCKER_IMAGE:$TRAVIS_TAG;
    fi
